export { default as LinkedStaffModeSwitch } from './LinkedStaffModeSwitch.vue'
export { default as EditorNoticeDialog } from './EditorNoticeDialog.vue'
export { default as NotationTypeConvertDialog } from './NotationTypeConvertDialog.vue'
/** @deprecated 使用 EditorNoticeDialog */
export { default as MusicXmlNoticeDialog } from './EditorNoticeDialog.vue'
export { default as ScoreNotationTypeSelector } from './ScoreNotationTypeSelector.vue'
export { default as BeginnerModeToolbar } from './BeginnerModeToolbar.vue'
export { default as EditModeToolbar } from './EditModeToolbar.vue'
export { default as PlayModeToolbar } from './PlayModeToolbar.vue'
export { default as PracticeModeToolbar } from './PracticeModeToolbar.vue'
export { default as ScoreToolbarShell } from './ScoreToolbarShell.vue'
